DROP TABLE IF EXISTS `purchase_payment`;
CREATE TABLE `purchase_payment` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `created_by` varchar(255) DEFAULT NULL,
  `created_date` datetime DEFAULT NULL,
  `deleted` bit(1) DEFAULT NULL,
  `uid` varchar(255) DEFAULT NULL,
  `updated_by` varchar(255) DEFAULT NULL,
  `updated_date` datetime DEFAULT NULL,
  `ver` int(11) DEFAULT NULL,
  `account_payable` double NOT NULL,
  `deduction_payment` double NOT NULL,
  `invoice_arrears` double NOT NULL,
  `pay_account` varchar(255) DEFAULT NULL,
  `pay_date` datetime DEFAULT NULL,
  `pay_no` bigint(20) NOT NULL,
  `pay_no_view` varchar(255) DEFAULT NULL,
  `pay_type` int(11) NOT NULL,
  `pay_way` varchar(255) DEFAULT NULL,
  `payment` double NOT NULL,
  `supplier` tinyblob,
  `organization_id` bigint(20) DEFAULT NULL,
  `purchase_order_id` bigint(20) DEFAULT NULL,
  `supplier_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_lhev9et69orkrctpflml58liu` (`organization_id`),
  KEY `FK_rswsgcwoi3fjdxmf7on317yjf` (`purchase_order_id`),
  KEY `FK_qmwo8nqsfhf1q6rebwuafcuwi` (`supplier_id`),
  CONSTRAINT `FK_lhev9et69orkrctpflml58liu` FOREIGN KEY (`organization_id`) REFERENCES `organization` (`id`),
  CONSTRAINT `FK_qmwo8nqsfhf1q6rebwuafcuwi` FOREIGN KEY (`supplier_id`) REFERENCES `supplier` (`id`),
  CONSTRAINT `FK_rswsgcwoi3fjdxmf7on317yjf` FOREIGN KEY (`purchase_order_id`) REFERENCES `purchase_order` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;